version: '{build}'

os:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
  - additional_flags: ""
  - additional_flags: "/std:c++latest"

matrix:
  exclude:
    - additional_flags: "/std:c++latest"
      os: Visual Studio 2015

init: []

install:
  - mklink test\files\link test\files\file
  - mklink test\files\broken_link test\files\broken
  - dir test\files
  - git submodule update --init --recursive

build_script:
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET GEN="Visual Studio 14 2015") ELSE (SET GEN="Visual Studio 15 2017")
  - cmake . -G%GEN% -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="%additional_flags%"
  - cmake --build . --config Release

test_script:
  - ctest -C Release -V
